networks:
  default: {}
  traefik:
    name: traefik
    external: true

services:
  switchboard:
    build: .
    container_name: switchboard
    restart: unless-stopped
    networks:
      - default
      - traefik
    environment:
      SWITCHBOARD_PUBLIC_URL: https://switchboard.example.com
      SWITCHBOARD_ADMIN_USERNAME: "${SWITCHBOARD_ADMIN_USERNAME:-admin}"
      SWITCHBOARD_GITSWITCHBOARD_TOKEN: "${SWITCHBOARD_GITSWITCHBOARD_TOKEN:-}"
    volumes:
      - ./.data:/data
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.switchboard.entrypoints: websecure
      traefik.http.routers.switchboard.rule: "Host(`switchboard.example.com`)"
      traefik.http.routers.switchboard.tls.certresolver: letsencrypt
      traefik.http.services.switchboard.loadbalancer.server.port: 8770
