networks:
  default: {}
  traefik:
    name: traefik
    external: true

services:
  hub:
    build: .
    container_name: hub
    restart: unless-stopped
    networks:
      - default
      - traefik
    environment:
      HUB_PUBLIC_URL: https://hub.example.com
      HUB_ADMIN_USERNAME: "${HUB_ADMIN_USERNAME:-admin}"
      HUB_GITHUB_TOKEN: "${HUB_GITHUB_TOKEN:-}"
    volumes:
      - ./.data:/data
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.hub.entrypoints: websecure
      traefik.http.routers.hub.rule: "Host(`hub.example.com`)"
      traefik.http.routers.hub.tls.certresolver: letsencrypt
      traefik.http.services.hub.loadbalancer.server.port: 8770
